# Generated by Django 3.2.5 on 2021-07-27 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0007_auto_20210727_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='shop_blog.blog'),
        ),
    ]
