# Generated by Django 3.2.5 on 2021-07-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0006_comment_create_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
