# Generated by Django 3.2.5 on 2021-08-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0015_chartsell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sell',
        ),
        migrations.DeleteModel(
            name='ChartSell',
        ),
    ]
