# Generated by Django 3.2.5 on 2021-08-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0016_auto_20210801_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='slider')),
            ],
        ),
    ]
