# Generated by Django 3.2.5 on 2021-07-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='name',
        ),
    ]
