# Generated by Django 3.2.5 on 2021-07-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0002_remove_contactus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('address', models.CharField(max_length=355)),
                ('email', models.EmailField(max_length=254)),
                ('about_us', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutus')),
            ],
        ),
    ]
