# Generated by Django 3.2.5 on 2021-07-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0003_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
