# Generated by Django 3.2.5 on 2021-07-31 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0005_alter_aboutus_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
