# Generated by Django 3.2.5 on 2021-07-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0003_itemorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='ItemOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
