# Generated by Django 3.2.5 on 2021-07-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0006_auto_20210723_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
