# Generated by Django 3.2.5 on 2021-07-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0008_coupon_itemorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
