# Generated by Django 3.2.5 on 2021-07-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0010_alter_order_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_price',
        ),
    ]
